services:
  backend: 
    image: touduc-vbs-backend:latest
    build:
      context: ./Backend             
      dockerfile: Dockerfile 
    container_name: touduc-vbs-backend
    volumes:
      - ./data:/workspace/data 
      - ./.cache/hf_cache:/root/.cache/huggingface 
      - ./Backend/app:/workspace/app
    ports:
      - "8000:8000"
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]